import type { NextPage } from 'next';
import Head from 'next/head';
import homeData from '../data/home.data.json';
import navData from '../data/navigation.data.json';
import footerData from '../data/footer.data.json';
import { PageProps } from '../types/interface';
import PageTemplate from '../lib/layout/pageTemplate';

const Home: NextPage<PageProps> = ({ page }) => (
  <div>
    <Head>
      <title> The Next Project </title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <PageTemplate page={{ ...page, ...navData, footerData: { ...footerData } }} />
  </div>
);

export const getStaticProps = () => {
  /* Imagining we are getting data from an api/backend, but here we provided it via home.data.json */
  const data = homeData;

  return {
    props: {
      page: data
    }
  };
};

export default Home;
