import type { NextPage } from 'next';
import Head from 'next/head';
import homeData from '../data/home.data.json';
import { PageProps } from './interface';
import PageTemplate from './pageTemplate';

const Home: NextPage<PageProps> = ({ page }) => (
  <div>
    <Head>
      <title> The Next Project </title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <PageTemplate page={page} />
  </div>
);


export const getStaticProps = () => {
  /* Imagining we are getting data from an api/backend, but here we provided it via home.data.json */
  const data = homeData

  return {
    props: {
      page: data
    }
  }
}

export default Home;
